// action type
export const GET_TELEPHONES = "GET_TELEPHONES"; 
export const DELETE_TELEPHONE = "DELETE_TELEPHONE"; 
export const ADD_TELEPHONE = "ADD_TELEPHONE"; 
export const GET_SINGLE_TELEPHONE = "GET_SINGLE_TELEPHONE"; 
export const UPDATE_TELEPHONE = "UPDATE_TELEPHONE"; 
export const GET_TYPES = "GET_TYPES"; 
export const GET_MARQUES = "GET_MARQUES"; 
